namespace Assets.Source.Structs.Scripts
{
    public enum ItemsType
    {
        Default,
        Blades2,
        Blades3,
        VRotators4,
        Box,
        Axe,
        BigRotator,
        Hook,
        ProppelerTramp,
        SpeedUp,
        Tramp,
        VRotator,
        Tube,
        AngledTube,
        SpiralTube,
        Mine,
        Column,
        Cone,
        Stair,
        Stair2,
        Cylinder,
        Ramp,
        Ramp2,
        Ring,
        Target,
        TrafficCone
    }
}
